baseURL = "http://example.org/"
languageCode = "en-us"
title = "JOSE & TRUMP "
theme = "minimal" 
publishDir = "docs"



[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1
    
    
    [[menu.main]]
    url = "/About/"
    name = "About"
    weight = 1
    
    
    [[menu.main]]
    url = "/Portfolio/"
    name = "Portfolio"
    weight = 1
    
    [[menu.main]]
    url = "/Contact/"
    name = "Contact"
    weight = 1
    